### ISSUE TITLE
args.ns should only be a name server name

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster-engine#102]
args.ns should always be only the nameserver name, now it is often a mix of ns/address.
If there is an address, split it out to args.address.

Any change must also update the logging string so that the address is not forgotten,

"Nameserver {ns} did not..." -> "Nameserver {ns}/{address} did not..."

This also affects all the translation strings.

**Comment by sandoche2k** [comment]
@pawal  - assign to VLE?

**Comment by sandoche2k** [comment]
@pawal Keep it open. Majority of them done.. but keep the issue open

**Comment by sandoche2k** [comment]
@pawal - moving it to 2015.4.

**Comment by matsduf** [comment]
It is a work in progress. AP to @vlevigneron updated this ticket on the status. Also see #60.

**Comment by sandoche2k** [comment]
@sandoche2K move to 2018

**Comment by matsduf** [comment]
PR #608 will resolve this issue.

**Comment by vlevigneron** [comment]
Fixed in https://github.com/zonemaster/zonemaster-engine/pull/608
