### ISSUE TITLE
usevc critical failure in Test/DNSSEC.pm

### ISSUE THREAD

**Issue by huguei** [zonemaster/zonemaster-engine#1028]
There's a critical failure exposed through a zonemaster.net live check:
https://zonemaster.net/result/480ccfd9cfd6e4e9
"SYSTEM - CRITICAL - Fatal error in Zonemaster::Engine::Test::DNSSEC: Can't call method "tc" on an undefined value at 
/usr/local/share/perl5/Zonemaster/Engine/Test/DNSSEC.pm line 2968."
The zone tested is "cl".

Thanks.

**Comment by huguei** [comment]
Not at all. I was able to replicate EDNS problems with one cloud provider for .cl in some nodes, but after some minutes the problems were gone. A glitch in the matrix, not so uncommon.
If it helps, I was getting timeout (no responses) with EDNS on queries to a v6 server.

**Comment by vlevigneron** [comment]
Fixed in zonemaster/zonemaster-engine#1029
