### ISSUE TITLE
Test crashes when name server name ends with a dot

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#1055]
If an undelegated test is started with a provided name server, the test will crash if the name server name ends with a dot. Compare:

```
$ zmb start_domain_test --domain iis.se --nameserver nsu.dnsnode.net.  # Name server name ends with a dot
{"id":1,"result":"20c83549f5bb74c6","jsonrpc":"2.0"}
```
```
$ zmb start_domain_test --domain iis.se --nameserver nsu.dnsnode.net  # The same data, but no dot at the end of the name server name 
{"result":"9b7cf489d032f653","jsonrpc":"2.0","id":1}
```

The first test (with dot) crashed:
```
$ zmb get_test_results --test-id 20c83549f5bb74c6 --lang en | jq .result.results
[
  {
    "message": "BACKEND_TEST_AGENT:UNSPECIFIED:UNABLE_TO_FINISH_TEST \n",
    "level": "CRITICAL",
    "module": "BACKEND_TEST_AGENT"
  }
]
```

The second test (without dot) runs as it should:
```
$ zmb get_test_results --test-id 9b7cf489d032f653 --lang en | jq .result.results
[
  {
    "module": "SYSTEM",
    "message": "Using version v4.4.0 of the Zonemaster engine.\n",
    "level": "INFO"
  },
  {
    "message": "Parent domain 'se' was found for the tested domain.\n",
    "level": "INFO",
    "module": "BASIC"
  },
  {
    "module": "BASIC",
    "level": "INFO",
    "message": "Nameserver nsu.dnsnode.net/2a01:3f0:400::32 listed these servers as glue: nsa.dnsnode.net., nsp.dnsnode.net., nsu.dnsnode.net..\n"
  },
  {
    "message": "Nameserver nsu.dnsnode.net/185.42.137.98 listed these servers as glue: nsa.dnsnode.net., nsp.dnsnode.net., nsu.dnsnode.net..\n",
    "level": "INFO",
    "module": "BASIC"
  },
(...)
]
```

**Comment by blacksponge** [comment]
After thinking about it I think it might be better to put the normalization step in backend and cli and keep the engine precondition as it is. Otherwise a test a NS with a final dot and a test without for the same parameters would be treated as different tests by backend.

**Comment by matsduf** [comment]
> After thinking about it I think it might be better to put the normalization step in backend and cli and keep the engine precondition as it is. Otherwise a test a NS with a final dot and a test without for the same parameters would be treated as different tests by backend.

That is a good point.

**Comment by pnax** [comment]
A similar issue exists: https://github.com/zonemaster/zonemaster-backend/issues/854

**Comment by matsduf** [comment]
Resolved by https://github.com/zonemaster/zonemaster-backend/pull/983 and https://github.com/zonemaster/zonemaster-cli/pull/253
