### ISSUE TITLE
Name server IPV6 wrongly reported "not answering"

### ISSUE THREAD

**Issue by Jeff777K** [zonemaster/zonemaster-engine#1085]
On my 2 nas Synology, I host my own public zone which can be contacted either by its IPV4 or its IPV6 IP.
The Basic and Connectivity sections of zone master report the IPV6 IP as not answering.
This was not the case three months ago (last time I did the test)
![Capture](https://user-images.githubusercontent.com/80906794/172385665-c1196978-b13a-4cf2-87ae-265c9e3e3043.JPG)
Regards.

**Comment by Jeff777K** [comment]
Thank you for your reply.
The two others tests are OK except for a warning  regarding the PTR of the IPV6. Which is normal since my FAI does’t provide IPV6 rDNS.

Envoyé à partir de Courrier pour Windows

De : Mats Dufberg
Envoyé le :mardi 7 juin 2022 15:26
À : zonemaster/zonemaster-engine
Cc : Jeff777K; Author
Objet :Re: [zonemaster/zonemaster-engine] Name server IPV6 wrongly reported"not answering" (Issue #1085)

It could be that there is some IP issue on IPv6 between the test site and the name servers. Did you test from https://zonemaster.net/? Could you compare with https://zonemaster.iis.se/? And https://zonemaster.dk-hostmaster.dk/?
Do you see the same problem in all places? If you can share the tested domain name with me over email (click on my profile picture and you will see my email) I could see what I can see.

**Comment by matsduf** [comment]
This issue has now been resolved. There was an routing issue that has now been corrected.
