### ISSUE TITLE
Clean up after dropping support for Net::IP

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#1129]
After we drop support for Net::IP in favor of Net::IP::XS in #1119 there are some things we need to clean up.

We need to take care of dependencies for new installations and upgrades. Also, the whole purpose of Zonemaster::Engine::Net::IP is gone so it should be deprecated and eventually removed.

* The installation instructions should be updated install Net::IP::XS instead of Net::IP. (#1130)
* An upgrade instruction should be added directing users to install Net::IP::XS when upgrading to the new version of Zonemaster::Engine.
* The API documentation for Zonemaster::Engine::Net::IP should state clearly that the module is deprecated and that it will be removed. It should also encourage people to migrate their code to use Net::IP::XS directly instead.

**Comment by matsduf** [comment]
>     * The installation instructions should be updated install Net::IP::XS instead of Net::IP.

See #1130.

**Comment by pnax** [comment]
> * The API documentation for Zonemaster::Engine::Net::IP should state clearly that the module is deprecated and that it will be removed.

Done with #1202
