### ISSUE TITLE
Incorrect handling of unknown option code in Nameserver11

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#1173]
In the specification of Nameserver11 it says

>      6. Else, if the "OPTION-CODE" from the query is present in the response,
>         then add name server to the *Returns Unknown Option Code* set.

(https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Nameserver-TP/nameserver11.md?plain=1#L114-L115)

In the code it is considered to be an error if there is any option-code in the response

```
            elsif ( defined $p->edns_data ) {
                push @unknown_opt_code, $ns->address->short;
```
(https://github.com/zonemaster/zonemaster-engine/blob/master/lib/Zonemaster/Engine/Test/Nameserver.pm#L1208-L1209)

That is probably an error since the response can include another option code, unrelated to the unknown option code included in the query.

The issue can be seen with abundo.se:
```
# zonemaster-cli --show-testcase --test nameserver/nameserver11 abundo.se --raw --level info
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.6.0
   0.82 WARNING   NAMESERVER11   N11_RETURNS_UNKNOWN_OPTION_CODE   ns_ip_list=195.196.175.218;195.196.175.219;2a00:ff40:1000:2::10;2a00:ff40:1000:2::11
```
When sending a query to e.g. 195.196.175.218 with an unknown option-code it is not included in the response:
```
# dig abundo.se soa @195.196.175.218 +norec +ednsopt=137:dead +mult +qr +nocookie

; <<>> DiG 9.18.9 <<>> abundo.se soa @195.196.175.218 +norec +ednsopt=137:dead +mult +qr +nocookie
;; global options: +cmd
;; Sending:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27204
;; flags: ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; OPT=137: de ad ("..")
;; QUESTION SECTION:
;abundo.se.		IN SOA

;; QUERY SIZE: 44

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27204
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 9

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 18 (Prohibited)

(...)
```

The EDE option is a different, not unknown option-code, added by the server.

**Comment by tgreenx** [comment]
Fixed by #1177
