### ISSUE TITLE
Zone08 erroneous message level

### ISSUE THREAD

**Issue by tgreenx** [zonemaster/zonemaster-engine#1275]
Currently [Zone08 can emit three message tags](https://github.com/zonemaster/zonemaster-engine/blob/7af3518b067890247aad29c4de90c1d45ee9bdf2/lib/Zonemaster/Engine/Test/Zone.pm#L136-L144): `MX_RECORD_IS_CNAME`, `MX_RECORD_IS_NOT_CNAME` and `NO_RESPONSE_MX_QUERY`.

`MX_RECORD_IS_CNAME` is logged as `INFO` level but that is probably an error. It should be logged as `WARNING` or `ERROR`. The [current Zone08 specification](https://github.com/zonemaster/zonemaster/blob/v2023.1.3/docs/public/specifications/tests/Zone-TP/zone08.md) does not have defined message tags, but says "If the MX answer is a CNAME, this test case fails.", which is a good indicator of incoherence.

The code can easily be updated to correct that before the specification is updated to the new template.

**Comment by matsduf** [comment]
As I read the code and understand the msgid, `MX_RECORD_IS_CNAME` is outputted when the mail exchange name has a CNAME, which is not permitted. Isn't it enough to update the profile and give it level `ERROR` while wating for the specification to be updated?
