### ISSUE TITLE
Incoherent argument type in function 'Zonemaster::Engine::Test/run_one()'

### ISSUE THREAD

**Issue by tgreenx** [zonemaster/zonemaster-engine#1278]
When running the Test suite, [Zonemaster::Engine::Test](https://github.com/zonemaster/zonemaster-engine/blob/v4.7.2/lib/Zonemaster/Engine/Test.pm) will run either:
- the full suite (using [run_all_for()](https://github.com/zonemaster/zonemaster-engine/blob/v4.7.2/lib/Zonemaster/Engine/Test.pm#L63))
- a specific Test module (using [run_module()](https://github.com/zonemaster/zonemaster-engine/blob/v4.7.2/lib/Zonemaster/Engine/Test.pm#L113))
-  a specific Test Case (using [run_one()](https://github.com/zonemaster/zonemaster-engine/blob/v4.7.2/lib/Zonemaster/Engine/Test.pm#L155)). 
 
The first two take at least one argument which is a `Zonemaster::Engine::Zone` object. However, the latter takes an array of `Zonemaster::Engine::Zone` objects (under the variable `@arguments`). I don't see why that is. From what I have seen all Test Cases only ever handle one argument (which is a `Zonemaster::Engine::Zone` object).

It has no sizable effect in practice but this part of the code should probably be harmonized.

**Comment by matsduf** [comment]
> The first two take at least one argument which is a `Zonemaster::Engine::Zone` object. However, the latter takes an array of `Zonemaster::Engine::Zone` objects (under the variable `@arguments`). I don't see why that is. From what I have seen all Test Cases only ever handle one argument (which is a `Zonemaster::Engine::Zone` object).

Isn't the idea that the third can run an array oif specific test cases?
