### ISSUE TITLE
BASIC01 does not find parent domain when testing an .arpa-domain

### ISSUE THREAD

**Issue by repperille** [zonemaster/zonemaster-engine#1280]
When starting a normal test with the .arpa-domain
0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa
the test fails in BASIC01 with B01_NO_CHILD even though it is a sone
(https://zonemaster.se/en/result/d308120abac1f3de)

$ dig soa 0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa
...
;; ANSWER SECTION:
0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa. 206 IN SOA    ns.nta.no. root.nta.no. 2023081801 28800 7200 1209600 86400

The same error (B01_NO_CHILD) happens when testing the parent zone
0.0.7.0.1.0.0.2.ip6.arpa
(https://zonemaster.se/en/result/0e98155738848971)

$ dig soa 0.0.7.0.1.0.0.2.ip6.arpa
...
;; ANSWER SECTION:
0.0.7.0.1.0.0.2.ip6.arpa. 2001  IN      SOA     ns.uninett.no. hostmaster.uninett.no. 2023082303 36000 3600 1814400 900

But it works when testing the parent of the parent!
7.0.1.0.0.2.ip6.arpa
(https://zonemaster.se/en/result/42f9f0f035fa5f16)

$ dig soa 7.0.1.0.0.2.ip6.arpa
...
;; ANSWER SECTION:
7.0.1.0.0.2.ip6.arpa.   1044    IN      SOA     pri.authdns.ripe.net. dns.ripe.net. 1692256305 3600 600 864000 3600

**Comment by matsduf** [comment]
Something is in error when Zonemaster cannot find the parent zone in this case:
```
$ zonemaster-cli 0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa
Seconds Level    Testcase       Message
======= ======== ============== =======
   0.00 INFO     UNSPECIFIED    Using version v4.7.2 of the Zonemaster engine.
   4.79 WARNING  BASIC01        The parent zone cannot be determined on name servers "".
   4.80 ERROR    BASIC01        "0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa" does not exist as a DNS zone. Try to test "0.9.0.0.0.7.0.1.0.0.2.ip6.arpa" instead.
   8.49 CRITICAL UNSPECIFIED    Not enough data about 0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa was found to be able to run tests.

$ zonemaster-cli 0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa --raw
   0.00 INFO     UNSPECIFIED    GLOBAL_VERSION   version=v4.7.2
   4.69 WARNING  BASIC01        B01_PARENT_UNDETERMINED   ns_ip_list=
   4.69 ERROR    BASIC01        B01_NO_CHILD   domain_child=0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa; domain_super="0.9.0.0.0.7.0.1.0.0.2.ip6.arpa"
   8.10 CRITICAL UNSPECIFIED    CANNOT_CONTINUE   domain=0.0.9.0.0.0.7.0.1.0.0.2.ip6.arpa
```
