### ISSUE TITLE
Do not query root for IANA special reserved names

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster-engine#170]
http://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml

**Comment by matsduf** [comment]
Would require a specification first.

**Comment by matsduf** [comment]
There are no problem for Zonemaster to handle undelegated, non-existing domains or domains not meant for usage. There are too little information in the issue. Will not fix. The requestor can come back with more information if there is something that we have not seen.
