### ISSUE TITLE
DNSSEC Key Size

### ISSUE THREAD

**Issue by stirnim** [zonemaster/zonemaster-engine#227]
It seems that zonemaster does not check the RSA key size yet. RFC 5072 states:

>    For interoperability, as in [RFC3110], the key size of RSA/SHA-256
>    keys MUST NOT be less than 512 bits and MUST NOT be more than 4096
>    bits.

for example key.seckle.ch uses an RSA key size of 4104 bits and zonemaster does not issue a WARNING about this.

====
Comment 2019-06-28: Correct RFC is [RFC 5702](https://tools.ietf.org/html/rfc5702#section-2). /@matsduf

**Comment by matsduf** [comment]
On hold until TC is created.

**Comment by sandoche2k** [comment]
Refer to https://github.com/dotse/zonemaster/issues/494

**Comment by sandoche2k** [comment]
TC to be created @sandoche2k @matsduf

**Comment by matsduf** [comment]
PR zonemaster/zonemaster#783 is the first step to solve this issue.

**Comment by vlevigneron** [comment]
@matsduf  PR approved, I start the implementation.

**Comment by matsduf** [comment]
New TC created by zonemaster/zonemaster#494. For implementation of TC refer to #584.
