### ISSUE TITLE
Create meta format for .po translation files

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#254]
Today we have four separate .po translation files, en.po, fr.po, fr_FR.UTF-8.po and sv.po. All files must have exactly the same message IDs ("msgid"), which are actually the default message in English from the code. When new messages are added, the msgid must be added to all .po files. Today we have:

From en.po:
```
#: BASIC:DOMAIN_NAME_LABEL_TOO_LONG
msgid  "Domain name ({dname}) has a label ({dlabel}) too long ({dlength}/{max})."
msgstr "Label ({dlabel}) in domain name ({dname}) is too long ({dlength}/{max})."
```
From fr.po:
```
#: BASIC:DOMAIN_NAME_LABEL_TOO_LONG
msgid  "Domain name ({dname}) has a label ({dlabel}) too long ({dlength}/{max})."
msgstr "Le nom de domaine ({dname}) a un label ({dlabel}) trop long ({dlength}/{max})."
```
From sv.po:
```
#: BASIC:DOMAIN_NAME_LABEL_TOO_LONG
msgid  "Domain name ({dname}) has a label ({dlabel}) too long ({dlength}/{max})."
msgstr "Domändelen {dlabel} i domännamnet {dname} är för lång ({dlength}/{max})."
```

I suggest that we create a meta format so that we have one file with all translations, and then in the build/installation process have a script that creates the individual .po files. E.g.

```
#: BASIC:DOMAIN_NAME_LABEL_TOO_LONG
msgid  "Domain name ({dname}) has a label ({dlabel}) too long ({dlength}/{max})."
:en: "Label ({dlabel}) in domain name ({dname}) is too long ({dlength}/{max})."
:fr: "Le nom de domaine ({dname}) a un label ({dlabel}) trop long ({dlength}/{max})."
:sv: "Domändelen {dlabel} i domännamnet {dname} är för lång ({dlength}/{max})."
```

Why are there two files for French? fr.po and fr_FR.UTF-8.po are identical.

**Comment by pawal** [comment]
This is pretty much a duplicate of #191.

**Comment by mattias-p** [comment]
For reference, here's documentation for the PO format: https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

**Comment by sandoche2k** [comment]
@mattias-p If i remember correctly we decided to have a single file. Isn't it? Can you take a look at this issue?

**Comment by matsduf** [comment]
@sandoche2k, it is on me.

**Comment by mattias-p** [comment]
@sandoche2k, I would like to look into using gettext more like it's supposed to be used. Like working with gettext instead of against it. But that's a larger task.

**Comment by matsduf** [comment]
@mattias-p, I have nothing against using gettext in a better way. I see using a single file as some kind of work-around, not working against gettext, but using a side track.

**Comment by mattias-p** [comment]
@matsduf, I don't mind. I just wanted to respond to @sandoche2k.

**Comment by matsduf** [comment]
The proposal here is not relevant anymore since we have found other ways to hand it. E.g. see #631 and #635.
