### ISSUE TITLE
Let the code emit message tags instead of messages

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#255]
1. Today the test code emits messages in various situations. The are emitted with variables, and are then handled by the translations system. As an example, Zonemaster/Test/Basic.pm emits the message below under some conditions (errors). That exact message is then the msgid for the translation system. In most cases the English translation just return the same message, but in this case the message is "translated" (rephrased).
```
Domain name ({dname}) has a label ({dlabel}) too long ({dlength}/{max}).
```

2. Connected to the message  there is also a tag, which is uniq within the leve (e.g. Basic). The tag for the above message is DOMAIN_NAME_LABEL_TOO_LONG. Two different tags can, in principle, have the same message, which can create problem for the translation (the translations might be different). 

3. With the level we can create a tag which is uniq in Zonemaster, e.g. BASIC:DOMAIN_NAME_LABEL_TOO_LONG.

4. I suggest that we migrate to use the extended tags instead of messages as msgids and let the translation mechanism do the entire work to transform from tag to message. Example of what the code should emit:
```
BASIC:DOMAIN_NAME_LABEL_TOO_LONG {dname} {dlabel} {dlength} {max}
```

5. With tags it will be clear if there is no working translation. Today, in English, we get something that looks correct, but might not be correct.

6. We clearly separate the message from the code. Instead we can define the tags in the Test Cases. In that way we more clearly define the outcome of the Test Cases. Then we can look at the Test Case to find out what the message should be.

**Comment by pawal** [comment]
If you follow a strict gettext workflow, you generate translation files indicating exactly what has changed in the code at any time. If the original string has changed, this is reflected in the translation files. Any gettext tool can then pick it up and give the translator good help in what to change. This includes fuzzy matching with a good proposal for translation.

This also means that it would be easier to use external translating tools such as Transifex or Lingohub.

My advice is to remove tags for translations entirely and only use strings. Tags are for logging and machine readability.

**Comment by matsduf** [comment]
I took a look at both Transifex and Lingohub (created trial accounts). I do not see that those would help us.

**Comment by sandoche2k** [comment]
@sandoche2K move it to 2018

**Comment by matsduf** [comment]
Won't fix.
