### ISSUE TITLE
Performance is worse with the latest version

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster-engine#274]
Upgrading from Engine version 1.0.14 to version 1.0.16 has given me a performance degradation.

Previously with 1.0.14 running Zonemaster in parallel for 1528 TLDs:
```
real    73m32.336s
user    277m8.170s
sys     2m29.920s
```

Now the same run with version 1.0.16:
```
real    98m26.622s
user    378m14.850s
sys     2m41.610s
```

Why does not Zonemaster use Net::IP::XS even though it is available?

Do you not run performance benchmarks between releases?

**Comment by matsduf** [comment]
Based on issue #174 Net::IP::XS was removed in Release 1.0.15, see https://github.com/dotse/zonemaster-engine/blob/master/Changes.

We could consider adding Net::IP::XS again, in some way or another, if requested.

**Comment by pawal** [comment]
Consider it requested. The original goal was to use Net::IP::XS rather than Net::IP if it was available. Also, we one priority for Zonemaster was performance, but perhaps that changed.

**Comment by pawal** [comment]
See #293 and #294.

**Comment by sandoche2k** [comment]
Refer to #293
