### ISSUE TITLE
Make use of Net::IP::XS if available

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster-engine#293]
For performance reasons, please use Net::IP::XS if it is available to the Perl version running.

There has been a serious performance degradation since introducing Net::IP instead of Net::IP::XS.

**Comment by sandoche2k** [comment]
@vlevigneron we did discuss about this issue. But I do no recall the decision. Do you think this issue is still valid?

**Comment by vlevigneron** [comment]
Fixed in https://github.com/zonemaster/zonemaster-engine/pull/565 which has been merged
