### ISSUE TITLE
Bug in checking for delegation size?

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#353]
Checking tccsetup.com **sometimes** return

```The smallest possible legal referral packet is larger than 512 octets (it is 536). ```

which does not seem to be correct. See https://zonemaster.net/test/899dfc7e24e52c94. The delegation is

```
$ dig tccsetup.com @d.gtld-servers.net +notcp +noedns

; <<>> DiG 9.9.5-3ubuntu0.12-Ubuntu <<>> tccsetup.com @d.gtld-servers.net +notcp +noedns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46848
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 8, ADDITIONAL: 6
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;tccsetup.com.			IN	A

;; AUTHORITY SECTION:
tccsetup.com.		172800	IN	NS	ns1.p17.dynect.net.
tccsetup.com.		172800	IN	NS	ns3.p17.dynect.net.
tccsetup.com.		172800	IN	NS	ns2.p17.dynect.net.
tccsetup.com.		172800	IN	NS	ns4.p17.dynect.net.
tccsetup.com.		172800	IN	NS	ns-420.awsdns-52.com.
tccsetup.com.		172800	IN	NS	ns-859.awsdns-43.net.
tccsetup.com.		172800	IN	NS	ns-1150.awsdns-15.org.
tccsetup.com.		172800	IN	NS	ns-1844.awsdns-38.co.uk.

;; ADDITIONAL SECTION:
ns1.p17.dynect.net.	172800	IN	A	208.78.70.17
ns3.p17.dynect.net.	172800	IN	A	208.78.71.17
ns2.p17.dynect.net.	172800	IN	A	204.13.250.17
ns4.p17.dynect.net.	172800	IN	A	204.13.251.17
ns-420.awsdns-52.com.	172800	IN	A	205.251.193.164
ns-859.awsdns-43.net.	172800	IN	A	205.251.195.91

;; Query time: 33 msec
;; SERVER: 2001:500:856e::30#53(2001:500:856e::30)
;; WHEN: Fri Dec 01 14:31:29 UTC 2017
;; MSG SIZE  rcvd: 346
```

**Comment by vlevigneron** [comment]
@matsduf This is not a bug, this is a feature... :-)
The size is calculated with the longest possible name in query in delegation03. I do not know if such a name exist in this case. For instance, if the following name 
 afqlydwrnmhhovdptoyjrzmxyjelvofnjoubtymhyqbpiegv.inblxeiomescitgfhtpotexszzhgzpohrewrocjnfqtjityxtecxklonedetjwh.icfxazxkffjaopkqyxwkdtazgifiguedgpbndrtltnurscdrvbwmkzfwkdtmulk.rmfbofsplcaztktjroyehgfmioxrfpxfkojofgwqtktkzaisovbnmrpkcuxjkyd.tccsetup.com

 exists and if we query it, the size of packet would be 537 bytes with the actual delegation.

**Comment by matsduf** [comment]
I agree. It follows the specification https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Delegation-TP/delegation03.md
