### ISSUE TITLE
Store recorded data in JSON

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#365]
Zonemaster Engine has support for recording and storing DNS responses in .data files.
These files have a simple line oriented format with three space-separated columns where the third field is a JSON encoded data structure.
While it's not difficult to operate on these files with standard tools such as `grep`, `sed`, `jq` and text editors, it's a fair amount of work to perform simple tasks.

@matsduf suggested that the situation could be much improved if they were JSON all the way up. I strongly agree with this. If they were all JSON you could do all the processing with `jq` which is an incredibly powerful tool once you get the hang of its query language.

The utility of this change is only limited by `jq`'s inability to penetrate base64 encoded DNS wireformat. Notwithstanding, this is still a big improvement.

**Comment by matsduf** [comment]
Replaced by #938
