### ISSUE TITLE
Update translator instruction

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#372]
The [translator instruction](https://github.com/dotse/zonemaster-engine/blob/develop/docs/Translation.pod#for-translators) is not up to date with current practices. The instruction must updated to take #358 into account.

**Comment by sandoche2k** [comment]
@mattias-p close?

**Comment by mattias-p** [comment]
At this time the translation instruction does not reflect our practices. For instance the instruction states that `en.po` should be generated by `extract_po.pl` and never be edited by hand, but that's not how we work today. See https://github.com/dotse/zonemaster-engine/issues/358#issuecomment-360427599.

**Comment by matsduf** [comment]
@mattias-p, is this issue relevant anymore? See issue #594 and merged PR #701.

**Comment by matsduf** [comment]
Instructions are updated.
