### ISSUE TITLE
Profiles in Engine

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#383]
The behavior of Zonemaster Engine is configurable with regard to what tests are performed, how they are performed, and how the results are analyzed.

Today this configurability is split up into config and policy. However there is no documentation on the reason for the separation nor on how each part works. Also the config and policy differ with regards to file locations.

There must be proper documentation for the configurability.

This is the Engine part of dotse/zonemaster#498.

**Comment by sandoche2k** [comment]
@mattias-p closed?
