### ISSUE TITLE
Replace Github service Travis

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#407]
Github services are deprecated. The repo uses Github service to get the Travis function. We need to update before the end-date.

https://developer.github.com/changes/2018-04-25-github-services-deprecation/
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by sandoche2k** [comment]
@mtoma this is a recurrent issue for all components. Can you check whether we need to really replace travis

**Comment by matsduf** [comment]
Travis is still working. We close this.
