### ISSUE TITLE
method4 should return parent zone glue address records, but returns address records of parent ns records

### ISSUE THREAD

**Issue by hno** [zonemaster/zonemaster-engine#424]
Noticed that zonemaster fails to detect mismatch of an A record between parent glue and zone data. Traced the error to method4 returning zone->glue which is an NSArray containing the parent zone ns records and resolved address records, not using glue address records at all.

Documentation for [Method 4](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Methods.md#method-4-obtain-glue-address-records-from-parent)  says it should use the parent zone glue address records. But the impemented method 4 returns an NSArray based on the parent NS records for the zone and looks up the corresponding address records.  zone->glue_addresses looks like it is the documented data for method4, but this is just address records and all tests using method4 (and 5) assumes they get an NSArray.

**Comment by hno** [comment]
Gah, text description of Method 4 actually matches current implementation, but not it's own title.

**Comment by matsduf** [comment]
A new implementation of methods will be created by #571.
