### ISSUE TITLE
Test for MANIFEST coverage

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#430]
One of the most common things we forget when making PRs and in code review is adding new files to either MANIFEST or MANIFEST.SKIP. We should have Travis test that - preferably as part of the usual test suite.

**Comment by matsduf** [comment]
This issue is in Zonemaster-Engine, but we have the same problem in all repos.

**Comment by sandoche2k** [comment]
@mattias-p can this issue be closed?

**Comment by mattias-p** [comment]
@sandoche2k Don't you think it would be useful? Or has it already been implemented and I'm just not aware of it?

**Comment by matsduf** [comment]
Done.
