### ISSUE TITLE
Cannot differentiate between REFUSED and no response

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#438]
Zonemaster::Engine::Nameserver::query returns `undef` for both DNS responses with status REFUSED and timeout (i.e. no response). In effect it's impossible for test cases to differentiate between those two conditions.

**Comment by matsduf** [comment]
This requires a fix in LDNS.

**Comment by mattias-p** [comment]
I cannot reproduce this. NAMESERVER01 emits "Erroneous response from nameserver" when it receives REFUSED responses.
