### ISSUE TITLE
Configurable levels in DNSSEC module

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#440]
Today the levels of the DNSSEC messages are hardcoded. The other modules allow the user to override their message levels. It must be possible to override the DNSSEC message levels with the usual mechanism.

**Comment by vlevigneron** [comment]
@mattias-p I guess it has been collaterally fixed by zonemaster/zonemaster-engine#527, no ?

**Comment by matsduf** [comment]
Yes, solved by #527.
