### ISSUE TITLE
Zonemaster wrongly does EDNS0 tests

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#442]
https://zonemaster.net/result/d1645a013e813d12

A related issue is opened here : https://github.com/zonemaster/zonemaster/issues/640

**Comment by pspacek** [comment]
Yeah, the result seems to be incorrect. Results from ednscomp are here: https://ednscomp.isc.org/ednscomp/482552aa23

**Comment by jelu** [comment]
Ping! Note that https://dnsflagday.net/ is approaching and it would be good if Zonemaster test correctly.

cc @matsduf

**Comment by sandoche2k** [comment]
We have discussed internally and we hope to implement the complete test before the end of january.

**Comment by sandoche2k** [comment]
Closed by EDNS0 work
