### ISSUE TITLE
Stop Engine from reporting config and policy in message

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#443]
Engine, in SYSTEM module, reports what config and policy has been loaded. The message includes full path. In CLI it looks the following:

```
Seconds Level     Module       Message
======= ========= ============ =======
   0.00 INFO      SYSTEM       Using version v2.0.7 of the Zonemaster engine.
   0.01 INFO      SYSTEM       Configuration was read from /usr/local/share/perl/5.18.2/auto/share/dist/Zonemaster-Engine/config.json.
   0.01 INFO      SYSTEM       Policy was read from /usr/local/share/perl/5.18.2/auto/share/dist/Zonemaster-Engine/policy.json.
```
Since those are just messages among other messages they go out via Backend and GUI. To prevent the leakage of file system information, the Backend tries to filter it out, but with mixed result. See issue zonemaster/zonemaster-backend#448.

The best work-around is to prevent Engine from reporting the files, and then look at the possibility to include some method that lets Engine to report to the clients (CLI and Backend) where the default profile is.

**Comment by pawal** [comment]
I would rather not remove this information, since it essential for other applications to know what policy was used. If you want to remove such information, filter out the SYSTEM module.

**Comment by matsduf** [comment]
I respect your comment, but filtering out the SYSTEM module is not the answer. 

What is your need? What if you can get the information with another call to the Engine API? Or are you using CLI? CLI already reports if you select another config or policy by option `--config` or `--policy`.

Do you need to know the file name, or do you want the actual policy/config? There is a `--dump_config` and `--dump_policy` from CLI, although the later has some bug at the moment (zonemaster/zonemaster-cli#90).

**Comment by matsduf** [comment]
Not relevant anymore.
