### ISSUE TITLE
Script to migrate config + policy to profile

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#445]
In issue #386 we have an upcoming update where config and policy are replaced by a profile. This change will be breaking. To make migration easier we have to create a script that can take a config file and a policy file and convert those into a profile file of the new format.

**Comment by sandoche2k** [comment]
@matsduf can we have an assignee to create this script?

**Comment by sandoche2k** [comment]
@vlevigneron to create a PR with the script

**Comment by matsduf** [comment]
The script is there  as zonemaster-engine/util/convert_config_to_profile.pl

**Comment by sandoche2k** [comment]
@matsduf test the script and close the issue

**Comment by sandoche2k** [comment]
@matsduf close?

**Comment by matsduf** [comment]
The script is there and has been improved by #512.
