### ISSUE TITLE
Avoid installing dependencies from CPAN in installation instruction

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#451]
For CentOS we're relying on CPAN for some runtime dependencies. This increases the burden of packaging Engine for CentOS.
The dependencies in question are:
* Locale::TextDomain - [Locale::TextDomain] 1.20 (perl-libintl) is available in CentOS but Engine requires 1.23. We should lower the requirement and add workarounds as needed.
* Mail::RFC822::Address - We should look into the possibility of migrating to [Email::Address] or [MailTools] (available from CentOS) or [Email::Valid] (available from EPEL).
* Text::CSV - Available from EPEL.

The mentioned potential replacements are available for all the other supported OSes.

For reference:
* [CentOS packages database]
* [Extra Packages for Enterprise Linux (EPEL)]

**Edit:** Lots of work has been done on dependencies since this issue was created and the old description was badly out of date, so I updated it to match the current state of things. (2019-04-08)

[CentOS packages database]: http://mirror.centos.org/centos/7/os/x86_64/Packages/
[Email::Address]: https://metacpan.org/pod/Email::Address
[Email::Valid]: https://metacpan.org/pod/Email::Valid
[Extra Packages for Enterprise Linux (EPEL)]: https://ftp.acc.umu.se/mirror/fedora/epel/7/x86_64/Packages/p/
[Locale::TextDomain]: https://metacpan.org/pod/Locale::TextDomain
[MailTools]: https://metacpan.org/pod/MailTools

**Comment by matsduf** [comment]
We get translation issues with lower versions of Locale::TextDomain. 1.23 was the lowest version that we verified that is works. I might be enough with 1.21, but 1.20 is too low.

**Comment by matsduf** [comment]
p5-Net-IP-XS version 0.21 is available on FreeBSD as a package.

**Comment by mattias-p** [comment]
Thanks @matsduf! I didn't realize the FreeBSD Ports Search was case sensitive.

**Comment by matsduf** [comment]
I suggest that this issue is renamed to cover all four OSs and be structed in the same way as the start of the description of zonemaster/zonemaster-backend#449. In that way we can synchronize between the OSs.

**Comment by matsduf** [comment]
Related to packaging of FreeBSD.
