### ISSUE TITLE
Inconsistent messages regarding net.ipv4 and net.ipv6

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#453]
Some test cases emit all of IPV4_DISABLED, IPV6_DISABLED, IPV4_ENABLED and IPV6_ENABLED (depending on circumstances) while other test cases only ever emit IPV4_DISABLED and IPV6_DISABLED.

Connectivity01 is an example of a test case that never emit IPV*_ENABLED. Basic02 is an example of a test cases that do emit IPV*_ENABLED.

We should make up our minds on whether the IPV*_ENABLED messages are useful.

**Comment by matsduf** [comment]
By design. Nothing to change.
