### ISSUE TITLE
Special key DISABLED in test_levels

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#454]
The `test_levels` option supports a special key `DISABLED`. It's somewhat similar to the `test_cases` option but works on the the module level. The `DISABLED` key is undocumented and to my knowledge the only place it is used is in the "disabled" "Example" in policy.json/profile.json.

If this feature is worth its weight, it should be documented.

See also #456.

**Comment by matsduf** [comment]
@mattias-p  will review to determine if still relevant.

**Comment by mattias-p** [comment]
This is still relevant.
```sh
grep -R '\bDISABLED' *
```

**Comment by matsduf** [comment]
PR #736 resolves this issue.
