### ISSUE TITLE
Make it possible to `use Zonemaster::Engine` in development context

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#457]
Today you can't `use Zonemaster::Engine` unless it's installed. I.e. you cannot use `perl -I` to point out a development version of Engine. This is inconvenient when you want to develop Engine and CLI on the same machine.

If the Zonemaster-Engine distribution isn't installed, dist files should be sought under the source repo instead of the installed dist file directory.

**Comment by matsduf** [comment]
Fixed by #458
