### ISSUE TITLE
issue when running zonemaster in Debian

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#476]
zonemaster-cli afnic.fr
Can't locate object method "effective" via package "Zonemaster::Engine::Profile" (perhaps you forgot to load "Zonemaster::Engine::Profile"?) at /usr/local/share/perl/5.20.2/Zonemaster/CLI.pm line 311, <DATA> line 20.

**Comment by vlevigneron** [comment]
@sandoche2k Could you please execute `zonemaster-cli --version` and send result please ?

**Comment by sandoche2k** [comment]
zonemaster-cli --version
CLI version:    v1.2.2
Engine version: v2.0.7

Test module versions:
	Address: v1.0.3
	Basic: v1.0.7
	Connectivity: v1.0.9
	Consistency: v1.1.2
	DNSSEC: v1.0.7
	Delegation: v1.0.8
	Example: v1.0.3
	Nameserver: v1.0.12
	Syntax: v1.0.3
	Zone: v1.0.3

**Comment by vlevigneron** [comment]
Engine version should be 2.0.12. Check if develop branch is well installed. It should fix the issue.

Envoyé depuis iHeure

**Comment by sandoche2k** [comment]
I have followed the method here to prepare the tar.gz file : https://github.com/sandoche2k/zonemaster/blob/834319f1d1d2e7b7b33108b02df2b009e41fc53a/docs/internal-documentation/distrib-testing/Centos-preparation.md

What i got after is : Zonemaster-Engine-v2.0.12.tar.gz
I copied the tar file to a new installed version of Debian and did a sudo cpanm Zonemaster-Engine-v2.0.12.tar.gz

The error that we have is on this machine.

**Comment by vlevigneron** [comment]
@sandoche2k It should work. but here is the result you should obtain :+1: 

```
CLI version:    v1.2.2
Engine version: v2.0.12

Test module versions:
	Address: v1.0.5
	Basic: v1.0.11
	Connectivity: v1.0.14
	Consistency: v1.1.6
	DNSSEC: v1.0.9
	Delegation: v1.0.11
	Example: v1.0.4
	Nameserver: v1.0.17
	Syntax: v1.0.5
	Zone: v1.0.6
```
I follow the same procedure (but on fedora), and I get the correct tar.gz. You should check there is no other version installed.
