### ISSUE TITLE
edns fails for afnic.fr ... seems to be false alert

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#480]
From Zonemaster CLI: 
```
9.27 WARNING   Nameserver ns2.nic.fr/192.93.0.4 accepts an unsupported EDNS version.
   9.28 WARNING   Nameserver ns3.nic.fr/192.134.0.49 accepts an unsupported EDNS version.
   9.30 WARNING   Nameserver ns1.nic.fr/192.134.4.1 accepts an unsupported EDNS version.
```
But EDNS compliance testing passes : https://ednscomp.isc.org/ednscomp/87d77657eb

**Comment by vlevigneron** [comment]
I just did a test and ran wireshark. What I can observe is that we send a packet with EDNS version 1 (which is not a valid vesion number) then we get an answer with NOERROR. According to the specs, the message you have is what is expected.

**Comment by sandoche2k** [comment]
I did a dig and i do not get that 
```
sandoche@sandoche:~$ dig +edns=1 soa afnic.fr @ns1.nic.fr

; <<>> DiG 9.10.3-P4-Ubuntu <<>> +edns=1 soa afnic.fr @ns1.nic.fr
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: BADVERS, id: 46168
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1432
;; QUESTION SECTION:
;afnic.fr.			IN	SOA

;; Query time: 1 msec
;; SERVER: 192.134.4.1#53(192.134.4.1)
;; WHEN: Fri Jan 18 23:55:20 CET 2019
;; MSG SIZE  rcvd: 37
```

**Comment by sandoche2k** [comment]
```
sandoche@sandoche:~$ dig +edns=1 soa afnic.fr @192.134.4.1

; <<>> DiG 9.10.3-P4-Ubuntu <<>> +edns=1 soa afnic.fr @192.134.4.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: BADVERS, id: 6251
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1432
;; QUESTION SECTION:
;afnic.fr.			IN	SOA

;; Query time: 1 msec
;; SERVER: 192.134.4.1#53(192.134.4.1)
;; WHEN: Fri Jan 18 23:57:43 CET 2019
;; MSG SIZE  rcvd: 37
```

**Comment by vlevigneron** [comment]
OK, I got it, Extended RCODE are not processed the same way in LDNS. I have to check both rcode and edns-rcode to compute RCODE value (perhaps we could improve specs to disambiguate that).

**Comment by sandoche2k** [comment]
I do not see how i could improve the specs "https://github.com/zonemaster/zonemaster/blob/develop/docs/specifications/tests/Nameserver-TP/nameserver10.md" 

Any inputs?

**Comment by vlevigneron** [comment]
@sandoche2k perhaps make a reference to both https://tools.ietf.org/html/rfc6891#section-9 and https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6.

**Comment by sandoche2k** [comment]
So, if i understand clearly, you want a reference to the RCODE BADVERS in Nameserver10?

**Comment by sandoche2k** [comment]
Ok.. I will add that for the respective specifications.

**Comment by sandoche2k** [comment]
Refer to https://github.com/zonemaster/zonemaster/issues/668
