### ISSUE TITLE
edns timeout is not captured by zonemaster

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#483]
Below the test result from DNS flag day tool :
https://ednscomp.isc.org/ednscomp/e2cdf14ee9

And result from Zonemaster below:
```
zonemaster-cli irisa.fr
Seconds Level     Message
======= ========= =======
  33.18 WARNING   No response from dns.irisa.fr/2001:660:7303:254::2 asking for irisa.fr.
  43.51 WARNING   No response from dns.irisa.fr/131.254.254.2 asking for irisa.fr.
  43.72 WARNING   No response from dns.irisa.fr/131.254.254.2 asking for irisa.fr.
  43.72 WARNING   No response from dns.irisa.fr/2001:660:7303:254::2 asking for irisa.fr.
  43.83 WARNING   No response from dns.irisa.fr/2001:660:7303:254::2 asking for irisa.fr.
  44.14 WARNING   No response from dns.irisa.fr/131.254.254.2 asking for irisa.fr.
```

**Comment by vlevigneron** [comment]
Isn't it related to https://github.com/zonemaster/zonemaster-engine/issues/438 ? If not, in which specific test case are we supposed to get a specific message for that ?

**Comment by matsduf** [comment]
What do you mean by "EDNS timeout"? If a server does not respond then you do not know anything about its EDNS status.

**Comment by sandoche2k** [comment]
@matsduf The timeout occurs when you send a query with edns version other than '0'.  With a query with edns version '0', i did get a response. 
Now, it seems they (irisa.fr) have corrected the issue. 
So, how does one differentiate a noresponse occurred due to edns @matsduf ?

**Comment by matsduf** [comment]
We should update the spec of NAMESERVER10 so that it does the same thing as NAMESERVER02.

**Comment by sandoche2k** [comment]
And add an issue in Zonemaster - Todo
