### ISSUE TITLE
Blacklisting of name servers that do not respond on EDNS queries

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#513]
There is a function in Engine that blacklists name servers that do not respond. The reason behind that is that it takes time to timeout, and instead of waiting for the same name server not responding several times Engine waits once and remember it.

There are name servers that do not respond on queries with OPT record (instead of returning FORMERR). We do not want to blacklist those. It could be possible to determine is if that kind from result of NAMESERVER02, i.e. if the server does not respond on the query with EDNS but does respond on the query with EDNS, then it should not be blacklisted.

What Test Cases use EDNS? I have identified that NAMESERVER{02,10-14} and DNSSEC** depend on EDNS and could cause unwanted blacklisting.

Also see issue #504.

**Comment by vlevigneron** [comment]
In fact we, as we do for the cache, we blacklist partially a nameserver. For instance, we can blacklist only TCP, not UDP. We can add the same mechanism for EDNS. We just have to pay attention to have few criteria if we want that the mechanism is still efficient.

**Comment by matsduf** [comment]
Fixed by #511.
