### ISSUE TITLE
Split message BROKEN_EDNS_SUPPORT in Nameserver02

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#516]
There are three different sub-cases in Nameserver02 that are tagged with BROKEN_EDNS_SUPPORT in the implementation, which prevents us from writing good messages for the users to be able to differentiate.

The specification has now been updated, which splits that message into three different messages throug zonemaster/zonemaster#749, which has been merged. See [Nameserver02] in develop branch.

Update the implementation to follow the updated specification.

[Nameserver02]: https://github.com/zonemaster/zonemaster/blob/develop/docs/specifications/tests/Nameserver-TP/nameserver02.md

**Comment by sandoche2k** [comment]
@matsduf to review and @vlevigneron close after his review

**Comment by sandoche2k** [comment]
@matsduf pls. review

**Comment by matsduf** [comment]
Solved by #517.
