### ISSUE TITLE
Output message not comprehensible

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#524]
https://www.zonemaster.net/result/75f85c13e5adc2f3
```
It says:
"ZONE	INFO	Target (A=94.198.159.39/AAAA=2a00:d78:0:712:94:198:159:39)
found to deliver e-mail for the domain name."
```

**Comment by matsduf** [comment]
1. What is missing for all messages is what Test Case that has outputted it.
2. The message is fine as a short message including the parameters. We should add a short description for each message. The description should not be printed by default, only on request (e.g. by clicking on the message).

**Comment by matsduf** [comment]
First step here is to have updated specifications of Zone08 and Zone09 that uses `MX_RECORD_EXISTS`.

**Comment by matsduf** [comment]
The message has already been updated.
