### ISSUE TITLE
Create a Engine->replay() method to test from cached data only.

### ISSUE THREAD

**Issue by mtoma** [zonemaster/zonemaster-engine#526]
Currently the engine dies when an external query is made with the no_network option.
For the purpose of replaying a test from data saved in the database it would be better to have a replay() method that would accept a string (instead of a cache file) and in case something is wrong with the provided cached data end properly with a system error in the output instead of dying.

**Comment by matsduf** [comment]
@vlevigneron, do you have a clear picture of what should be done to meet this issue and what we would gain?

**Comment by matsduf** [comment]
This has been fixed.
