### ISSUE TITLE
Pre-delegation testing issue

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#530]
Domain : 2stic.nl
NS : proteus.sidnlabs.nl.

Zonemaster.net : Did not test with the pre-delegated server. Currently, the NS is delegated and the issue is not reproducable. 

But, while testing with zonemaster.iis.se at the same moment it was able to test.

**Comment by matsduf** [comment]
This issue is related to zonemaster/zonemaster-gui#38.

**Comment by matsduf** [comment]
Cannot reproduce.
