### ISSUE TITLE
Missing messages in translation files (Delegation Tests)

### ISSUE THREAD

**Issue by vlevigneron** [zonemaster/zonemaster-engine#534]
There are 4 messages missing in translation files corresponding to the following labels:
ENOUGH_IPV4_NS_CHILD
ENOUGH_IPV4_NS_DEL
ENOUGH_IPV6_NS_DEL
ENOUGH_IPV6_NS_CHILD

**Comment by sandoche2k** [comment]
If I understand ... you want them to be added to the French, Swedish, and Danish? For French @vlevigneron and for Danish and Swedish @matsduf

**Comment by vlevigneron** [comment]
@matsduf It seems that only danish translation is missing.

**Comment by matsduf** [comment]
@vlevigneron, I will reformat and merge #636.

**Comment by matsduf** [comment]
Resolved.
