### ISSUE TITLE
make distcheck issue

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#538]
```
[zonemaster@vps323914 zonemaster-engine]$ make distcheck
/usr/bin/perl "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
No such file: share/locale/da/LC_MESSAGES/Zonemaster-Engine.mo
No such file: share/locale/en/LC_MESSAGES/Zonemaster-Engine.mo
No such file: share/locale/fr/LC_MESSAGES/Zonemaster-Engine.mo
No such file: share/locale/sv/LC_MESSAGES/Zonemaster-Engine.mo
```

**Comment by vlevigneron** [comment]
cd share/
make
cd ..
make distcheck

**Comment by sandoche2k** [comment]
In that case, it is not as per the process for preparing the tar file for testing the release. For all ZM repositories, I do make the distcheck from the main directory itself.

**Comment by vlevigneron** [comment]
Isn’t it possible to adapt the process ?

Envoyé depuis iHeure

**Comment by sandoche2k** [comment]
Yes, it is possible. Is this adaption just for this release or permanent?

**Comment by vlevigneron** [comment]
It should had already been there. I'm surprised it worked before.

**Comment by sandoche2k** [comment]
You are right. Previously we may have ignored the warnings. The effort currently is to remove all warnings.

**Comment by vlevigneron** [comment]
The solution could be ro remove the generated files from MANIFEST, aka :

share/locale/da/LC_MESSAGES/Zonemaster-Engine.mo
share/locale/en/LC_MESSAGES/Zonemaster-Engine.mo
share/locale/fr/LC_MESSAGES/Zonemaster-Engine.mo
share/locale/sv/LC_MESSAGES/Zonemaster-Engine.mo

and replace them by source files, aka :

share/da.po
share/en.po
share/fr.po
share/sv.po

No ?

**Comment by sandoche2k** [comment]
I am not able to reproduce it.
