### ISSUE TITLE
If a domain has a CNAME and the CNAME has NS, is the behavior of ZM correct?

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#539]
Below are a sequence of tests for the domain "中央大学.tw". dig:

```
[zonemaster@vps323915 network-scripts]$ zonemaster-cli 中央大学.tw
Seconds Level     Message
======= ========= =======
  13.49 CRITICAL  No NS records for tested zone from parent. NS tests aborted.
  13.50 CRITICAL  Not enough data about xn--fiq80yua78t.tw was found to be able to run tests.
```

But, the domain has a CNAME which has the NS

```
[zonemaster@vps323915 network-scripts]$ dig 中央大学.tw

; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> 中央大学.tw
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21794
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;中央大学.tw.		IN	A

;; ANSWER SECTION:
中央大学.tw.	3600	IN	CNAME	中央大學.tw.
中央大學.tw.	3600	IN	CNAME	www.ncu.edu.tw.
www.ncu.edu.tw.		21600	IN	A	140.115.17.82

```
The CNAME ncu.edu.tw. has the NS records
```
[zonemaster@vps323915 network-scripts]$ dig ncu.edu.tw -t NS +short
dns2.ncu.edu.tw.
dns.ncu.edu.tw.
```

**Comment by mattias-p** [comment]
Yes, I would say it is correct. `中央大学.tw.` is not a zone but rather an alias. Zonemaster only tests zones, so having it test an alias is effectively an out-of-range error.

Zonemaster quickly finds that `tw.` has no NS records for the domain name and concludes that nothing more can be done.

However I think Zonemaster could be more helpful in this situation. An additional CNAME query could be made, and if such a record is found it could be reported as an error with a parameter for the canonical name. This would provide the user more context about why an apparently working domain can't be tested.

**Comment by mattias-p** [comment]
I believe this can be closed. Please reopen otherwise.
