### ISSUE TITLE
Getting en.po msg-txt include in 'results' column in database

### ISSUE THREAD

**Issue by godzone** [zonemaster/zonemaster-engine#542]
Am I missing something?  I would like to see the text from en.po msgstr included with the test result e.g.
{
   "args": {
      "name":"agre.enterprises"
   },
   "level":"INFO",
   "module":"SYNTAX",
   "msgstr":"Neither end of any label in the domain name (agre.enterprises) has a hyphen."
   "tag":"NO_ENDING_HYPHENS",
   "timestamp":68.348419189451
}
I found the file en.po in the clone of the zonemaster-engine repo but it doesn't appear to have been installed anywhere after running 'make install'. So I am not sure how this can be included.

**Comment by sandoche2k** [comment]
@vlevigneron can you have a look?

**Comment by godzone** [comment]
Digging around some more, it would appear that the 'make install' doesn't actually copy the locale stuff into the production directories.  I copied blib/lib/auto/share to /usr/local/lib64/perl5/auto by hand.  It doesn't seem to have any effect on what Zonemaster-Engine logs for a test result.  So I guess the question is 'Should the logged result actually have the msg text already and I have something broken, or am I wanting something that is not in fact implemented?'

**Comment by sandoche2k** [comment]
@godzone sorry for the delay in response. @vlevigneron who is the principal developer of the engine is attending a conference. We will get a response to your questions soon.

**Comment by godzone** [comment]
Thinking some more about this overnight...

My end point is being able to display a meaningful message for a test result on a web page in our customer portal.  Having the message actually in the JSON structure in the test_result would work for me as I don't have too many domains but it wouldn't scale to 10,000s of domains, it would just consume disk space and make the zonemaster database unnecessarily large.

For me, looking up the module:code and then inserting any params into a message at the time the result is displayed would be far more efficient in terms of space.  So I think I will spend some time exploring this as an alternative option.

**Comment by godzone** [comment]
A little further information.  My issue really is not being able to easily join data from tables in different postgresql databases so I was running a process to move, and reformat the test_results table into our admin database.  I think I will still do this but will use the API call to get the results instead of a direct db query. I had considered putting the zonemaster tables in our admin db but even then doing joins against a table with JSON columns looked too hard.  Using the API gives me the message text but I lose the TAG and the test ARGS. For now I think the result will be better but it still isn't quite what I wanted.

**Comment by godzone** [comment]
By combining direct db access with using the JSON-RPC API, I have an acceptable solution.

**Comment by matsduf** [comment]
@godzone, at installation time the .po files are compied into .mo files. The .mo files are installed if everything is done as it should. You should be able to fine the following structure. Exactly where it is depends on the OS.

```
./Zonemaster-Engine
|-- config_example_logfilter.json
|-- iana-ipv4-special-registry.csv
|-- iana-ipv6-special-registry.csv
|-- locale
|   |-- da
|   |   `-- LC_MESSAGES
|   |       `-- Zonemaster-Engine.mo
|   |-- en
|   |   `-- LC_MESSAGES
|   |       `-- Zonemaster-Engine.mo
|   |-- fr
|   |   `-- LC_MESSAGES
|   |       `-- Zonemaster-Engine.mo
|   `-- sv
|       `-- LC_MESSAGES
|           `-- Zonemaster-Engine.mo
|-- profile.json
`-- profile_example_logfilter.json
```

When you query the Zonemaster-Backend for a test result you give the language you want to translated into and that is then returned in the response.

**Comment by godzone** [comment]
make install didn't copy these files, I don't know why but they were missing, I copied them by hand and then the result worked as intended. As mentioned, I had hoped to be able to get the translated result directly from the database but using the API call is now working for me instead.

**Comment by matsduf** [comment]
@godzone, I close this issue again, but if you have the issue again, please give a detailed description of what you have done and on what OS and version. Thank you for reporting.
