### ISSUE TITLE
Should required version be set in the code?

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#553]
Version v3.0.x of Zonemaster::Engine requires at least version v2.0.0 of Zonemaster::LDNS, but that is not stated in the code. It accepts any version. Wouldn't it be better to state that in e.g. Engine.pm to get a meaningful error message if wrong version is installed?

**Comment by mattias-p** [comment]
Do you have a really good reason for doing this? I think there are really good arguments for not doing it.

**Comment by mattias-p** [comment]
Please don't cross-post the same issue in all multiple repositories. And if you do, link all the issues to each other and point out which one of them is intended for discussion.

See zonemaster/zonemaster-cli#108 and zonemaster/zonemaster-backend#523. I've responded in zonemaster/zonemaster-backend#523, so please keep the discussion there.

**Comment by matsduf** [comment]
In this case there is no main repository. I see as natural to create issues in each case. Your are trying to make a hen out of a feather.

**Comment by matsduf** [comment]
Will not fix.
