### ISSUE TITLE
Confusing message about unreachable name server

### ISSUE THREAD

**Issue by aabdnn** [zonemaster/zonemaster-engine#563]
Hi folks,

Yesterday we had a strange case from a customer. They were attempting to delegate 241.57.193.in-addr.arpa to these 3 servers:

1. ns0.airfrance.fr
2. ns1.airfrance.fr
3. ns2.airfrance.fr

Their delegation was being blocked by our instance of Zonemaster, with the error message "Nameserver ns1.airfrance.fr/193.57.244.250 not accessible over UDP on port 
53."

So I immediately tried to query it myself, and when I did a SOA query for 241.57.193.in-addr.arpa, the name server replied. I even did NS queries, and it replied. However, when I ran the test using "zonemaster-cli", it kept failing.

So I used tcpdump to figure out what zonemaster was sending. It turns out that zonemaster was trying to figure out the AAAA record of ns0.airfrance.fr, so it was sending a AAAA query to the name server over UDP, and a firewall was dropping that query.

So neither the customer nor I could figure out the actual problem, because the error message was, in my opinion, vague.

Could zonemaster please emit a better message, such as "Nameserver ns1.airfrance.fr/193.57.244.250 did not answer AAAA query for ns0.airfrance.fr over UDP". In that case, the customer would not even have needed to contact us.

**Comment by matsduf** [comment]
There is a specific test case for this issue, [Nameserver05] ("Behaviour against AAAA query"), which should return QUERY_DROPPED ('Nameserver ns1.airfrance.fr/193.57.244.250 dropped AAAA query.'). Do you see that?

Can you see what Test Case (or at least level) that returns the message?

It is possible that we have an interesting interaction with Zonemaster blacklisting. If a nameserver does not respond to DNS query on a specific protocol (UDP/TCP) then Zonemaster will remember that and not query again to prevent a test to have too many timeouts.

[Nameserver05]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Nameserver-TP/nameserver05.md

**Comment by aabdnn** [comment]
Hi @matsduf. Here's what the CLI shows:

```
$ zonemaster-cli 241.57.193.in-addr.arpa --ns ns0.airfrance.fr --ns ns1.airfrance.fr --ns ns2.airfrance.fr --show_module --stop_level ERROR
Seconds Level     Module       Message                                                                                                                [195/1816]
======= ========= ============ =======
  21.02 NOTICE    BASIC        Nameserver ns1.airfrance.fr/193.57.244.250 did not respond to NS query.
  21.02 NOTICE    BASIC        Nameserver ns2.airfrance.fr/193.57.245.250 did not respond to NS query.
  21.97 ERROR     CONNECTIVITY Nameserver ns1.airfrance.fr/193.57.244.250 not accessible over UDP on port 53.
```

**Comment by matsduf** [comment]
I do see a specific message when I run the test. Maybe it should be a WARNING instead of NOTICE. Do you feel that the specific message is not enough?

```
# zonemaster-cli 241.57.193.in-addr.arpa --ns ns0.airfrance.fr --ns ns1.airfrance.fr --ns ns2.airfrance.fr --show_module
Seconds Level     Module       Message
======= ========= ============ =======
  35.41 ERROR     CONNECTIVITY Nameserver ns1.airfrance.fr/193.57.244.250 not accessible over UDP on port 53.
(...)
  71.97 NOTICE    NAMESERVER   Nameserver ns1.airfrance.fr/193.57.244.250 dropped AAAA query.
  71.98 NOTICE    NAMESERVER   Nameserver ns2.airfrance.fr/193.57.245.250 dropped AAAA query.
(...)
```

```
# zonemaster-cli --version
CLI version:    v2.0.1
Engine version: v3.0.3

Test module versions:
	Address: v1.0.5
	Basic: v1.0.11
	Connectivity: v1.0.14
	Consistency: v1.1.8
	DNSSEC: v1.0.10
	Delegation: v1.0.12
	Example: v1.0.4
	Nameserver: v1.0.23
	Syntax: v1.0.5
	Zone: v1.0.6
```

**Comment by matsduf** [comment]
@aabdnn, have you looked at my reply above? Do you feel that my [proposal](https://github.com/zonemaster/zonemaster/issues/778) to increase the default level of the message from notice to warning will solve the issue for you?

**Comment by matsduf** [comment]
@aabdnn, there is a PR now that will specify the AAAA error as ERROR. See zonemaster/zonemaster#787. Can we close this issue now?

**Comment by matsduf** [comment]
Resolved.
