### ISSUE TITLE
Add implementation of MethodsNT

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#571]
A new version of the methods, [MethodsNT], has been specified and added to the master branch. Before it can be used in test case specifications, [MethodsNT] must be implemented in Zonemaster-Engine.

Create all methods specified in [MethodsNT].

[MethodsNT]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/MethodsNT.md

**Comment by matsduf** [comment]
OK from F2F to continue.
@pamasse, @mattias-p, @mtoma and @sandoche2k, please review!
@vlevigneron, please make an estimate!

**Comment by mattias-p** [comment]
If possible this implementation should come with good coverage of unit tests.

**Comment by matsduf** [comment]
I think we can close this, and create any needed issues in Engine. Here is the first: https://github.com/zonemaster/zonemaster-engine/issues/1222
