### ISSUE TITLE
Clean up documentation on config and policy

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#574]
A while back we replaced config and policy with profiles. It seems we didn't bother to clean up the old documentation for the removed parts. There are still references to both policy and config all over the place. We should clean that up. In the process we should also make sure that whatever is removed is documented to the same level in the Profiles documentation. It would be a shame if the quality of our documentation dropped.

**Comment by matsduf** [comment]
@mattias-p, you created this issue in Zonemaster-Engine repository. Does that mean that you have only seen the problem in this repository?
