### ISSUE TITLE
Missing messages in the po files

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#576]
The messages from some test cases are missing in the po files. As exampel, the messages from Delegation01 and Delegation02 are completely missing. The messages from Delegation03 are partly missing.

**Comment by vlevigneron** [comment]
@matsduf Is it still relevant. I guess it has been adressed by last PR, no ?

**Comment by matsduf** [comment]
The PO files have been updated. This issue is no longer relevant.
