### ISSUE TITLE
Consistency05 does not report extra addresses at child

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#577]
[Consistency05] should report if there are IP addresses defined for in-bailiwick name servers not included in the glue records from the parent zone. From the test case:

> ii. If an IP from Address Records From Child is not listed in Delegation Strict Glue with that same name server name, then output EXTRA_ADDRESS_CHILD.

But the implementation does not report that, at least not in all cases. Issue zonemaster/zonemaster#764 made us aware of the situation.

**This text lacks reference to a real example. We have an example, but it cannot be revealed. An example must be constructed.**

[Consistency05]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Consistency-TP/consistency05.md

**Comment by vlevigneron** [comment]
@matsduf Just to be sure we are talking about the same thing. Do you thing that the zone consistency05-extra-address-child-1.zut-root.rd.nic.fr correspond to that specific case ?
(There's an additional IPv6 address in child zone not present in parent)

**Comment by matsduf** [comment]
Yes, that seems to be it.

(No reply from vps430862.ovh.net [145.239.76.202])

**Comment by vlevigneron** [comment]
You are right, vps430862.ovh.net needs to be fixed (server has been switched off by OVH days ago, it will take a little time before I fix that). But in this particular case, it changes nothing in the results of consistency05.

**Comment by matsduf** [comment]
Resolved by zonemaster/zonemaster-engine#593
