### ISSUE TITLE
Extend messages with test case

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#578]
### Background

A message outputted from a test case is local to the module, e.g. NO_RECURSOR belongs to module NAMESERVER and not to test case Nameserver01. This has some consequences:

1. A message cannot be traced back to the test case and its specification.
2. The same message tag (e.g. NO_RECURSOR) within the same module will have the same level, e.g. ERROR or INFO, but when the same message tag is used in different modules they are independent.

### Proposal

The test case is added as parameter to the message.

```
  {
    "args": {
      "address": "2001:67c:124c:100a::45",
      "ns": "ns.nic.se"
    },
    "level": "INFO",
    "module": "NAMESERVER",
    "tag": "NO_RECURSOR",
    "timestamp": 8.46649193763733
  },
```

Will be fixed by #762.

**Comment by matsduf** [comment]
> I chose 'test_case' for the moment but it could be 'method' which is also used elsewhere in documentation.

I think that "test case" is the correct reference since that is what we call the specifications in Zonemaster/Zonemaster. Where do you see "method"?

I suggest "testcase" instead of "test_case" to make it easier to read and write, just as "time stamp" is written as "timestamp".

**Comment by vlevigneron** [comment]
> > I chose 'test_case' for the moment but it could be 'method' which is also used elsewhere in documentation.
> 
> I think that "test case" is the correct reference since that is what we call the specifications in Zonemaster/Zonemaster. Where do you see "method"?
> 

In CLI documentation, it is written : 
`'Specify test to run. Should be either the name of a module, or the name of a module and the name of a method in that module separated by a "/" character (Example: "Basic/basic1"). The method specified must be one that takes a zone object as its single argument. This switch can be repeated.'
`
> I suggest "testcase" instead of "test_case" to make it easier to read and write, just as "time stamp" is written as "timestamp".

OK, if we decide it is not  "method" I will use "testcase" with no space.

**Comment by matsduf** [comment]
@vlevigneron, good catch of the inconsistency of terminology. We should update to be consistent. What document so that I can create an issue, or you do it?

**Comment by vlevigneron** [comment]
@matsduf https://github.com/zonemaster/zonemaster-cli/blob/master/lib/Zonemaster/CLI.pm#L163

**Comment by matsduf** [comment]
Issue for the terminology inconsistency is created as 
https://github.com/zonemaster/zonemaster-cli/issues/123.

**Comment by matsduf** [comment]
Proposal accepted by F2F.

@matsduf to create issues in GUI on next step, i.e. creating links back to test case specifications.

**Comment by mattias-p** [comment]
Another argument for "testcase" over of "test_case" is that it's in line with "keytag" and "timestamp".
