### ISSUE TITLE
No info about missing IPv6 glue

### ISSUE THREAD

**Issue by pos42** [zonemaster/zonemaster-engine#581]
zonemaster is such a great tool and saves a lot of manual work when testing!

I can see there is info if a dns PTR does not match. No error, but good info when testing.... However... It would also be good to know if you have made a misconfiguration in the IPv6 glue. I have a customer which registrar did not even add ip fields for the delegation, even though the dns servers were in the delegated domain itself. They however looked up and added ipv4 addresses automatically.... So therefor the IPv6 glue was forgotten as it was not added automatically as the ipv4. No info at all in the registrar gui. It is actually the registrar that took over domains from .SE registrar service.

Now..
Using zonemaster it would be really great if zonemaster could react and at least give an info hint that the dns servers has an authoritative IPv6 address that is not listed in the  parent delegation. That would be very good help to quickly solve the issue.

Info presented like:
se to domain.se: Authoritative AAAA records exist for ns1.domain.se, but there are no corresponding AAAA glue records.
se to domain.se: Authoritative AAAA records exist for ns2.domain.se, but there are no corresponding AAAA glue records.

would be nice....

**Comment by vlevigneron** [comment]
Fixed in https://github.com/zonemaster/zonemaster-engine/pull/593
