### ISSUE TITLE
No info or warning if glue address differs from authoritative address

### ISSUE THREAD

**Issue by pos42** [zonemaster/zonemaster-engine#582]
A warning or info would be good if glue address differs from authoritative address.

Let´s say you have host ns.mydomain.se with IP 1.2.3.4 in glue for the domain mydomain.se. Then if you look up ns.mydomain.se and it gives you another IP, I think it should generate at least a note. Ok, the IP:s could be on the same name server and cause no real problem. But still I think it should be noted by zonemaster at the info level.

I have seen this recently.

/Peo

**Comment by matsduf** [comment]
Test Case [CONSISTENCY05] considers mismatch to be an ERROR. If Zonemaster does not discover that we have a bug in the implementation. @pos42, do you have an example of a domain that have that error?

[CONSISTENCY05]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Consistency-TP/consistency05.md

**Comment by pos42** [comment]
@matsduf  Cannot mention the customer. But I can describe better.

Let say you dig at a parent server (i.e SE server). Like "dig domain.se ns @x.ns.se". You will see the name servers and the additional section with the IPs. The name servers for domain.se are within its own domain (i.e glue IP is added). Let's say ns1.domain.se and ns2.domain.se. So you will in this dig get the name servers and in the additional section their IPs.

Now... If you do a "dig ns1.domain.se +short" you will get a different IP for ns1.domain.se than what is seen in the glue.

I think a setup like this should render into at least a note in zonemaster. Have tried both zonemaster.net and zonemaster.iis.se (if they have different versions).

So if you expect CONSISTENCY05 to track this down, i guess it is a bug in the zonemaster check.

So I guess it is very easy for you to test this. Just have two IPs on the nameserver and use one in the glue and the other in the zone A record :)

/Peo

**Comment by matsduf** [comment]
Zonemaster (CONSISTENCY05) considers that to be an ERROR and should report it as such. Thank you for reporting the bug.

**Comment by matsduf** [comment]
@vlevigneron, zone.G00.consistency05.data.zonemaster.se has the error but Zonemaster does not report it.

**Comment by vlevigneron** [comment]
With my fix, I get:
   7.58 NOTICE    Child has extra nameserver IP address(es) not listed at parent (ns6.zone.g00.consistency05.data.zonemaster.se./2001:67c:124c:205a::133;ns6.zone.g00.consistency05.data.zonemaster.se./91.226.37.133).

**Comment by matsduf** [comment]
What fix?

zone.g00.consistency05.data.zonemaster.se should report "IN_BAILIWICK_ADDR_MISMATCH".

**Comment by vlevigneron** [comment]
It reports both:
  

>  7.30 ERROR     CONSISTENCY:IN_BAILIWICK_ADDR_MISMATCH parent_addresses=ns6.zone.G00.consistency05.data.zonemaster.se./2001:67c:124c:100a::57;ns6.zone.G00.consistency05.data.zonemaster.se./91.226.36.57; zone_addresses=ns6.zone.g00.consistency05.data.zonemaster.se./2001:67c:124c:205a::133;ns6.zone.g00.consistency05.data.zonemaster.se./91.226.37.133
>    7.30 NOTICE    Child has extra nameserver IP address(es) not listed at parent (ns6.zone.g00.consistency05.data.zonemaster.se./2001:67c:124c:205a::133;ns6.zone.g00.consistency05.data.zonemaster.se./91.226.37.133).
>

**Comment by vlevigneron** [comment]
I have not pushed the diff in the repo yet. The fact is that it seems the problem comes from "methods". We will not have time to rewrite all of them for the next release, so I will propose a workaround just for this case. Less "smart" that the current one, but more easy to understand and modify in case we need some "adjustments".
Should I link the PR to this issue or with zonemaster/zonemaster-engine#577

**Comment by matsduf** [comment]
@vlevigneron, when it comes to methods I think the way to go is to look at "Add implementation of MethodsNT" (#571), currently scheduled for v2019.3.

If the PR fixes both it should issues refer to both.

**Comment by matsduf** [comment]
The zone zone.G01.consistency05.data.zonemaster.se should also report "IN_BAILIWICK_ADDR_MISMATCH".

**Comment by vlevigneron** [comment]
> @vlevigneron, when it comes to methods I think the way to go is to look at "Add implementation of MethodsNT" (#571), currently scheduled for v2019.3.
> 
I agree but we have to wait (at leas) t3 months more to have them implemented.

> If the PR fixes both it should issues refer to both.

It was the case in the comment, I modified PR title accordingly.

**Comment by matsduf** [comment]
Resolved by zonemaster/zonemaster-engine#593
