### ISSUE TITLE
Updates to translation documentation

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#594]
There are things I'd like to update in the translation documentation:
* Workflow: Have programmers only update source code and translators only update PO files.
* New use case: Describe the steps to add a new language.

Edit: I removed the translator specific item as that's covered by #591.

**Comment by matsduf** [comment]
Overlaps with #591.

**Comment by mattias-p** [comment]
Ah, I missed that one. Do you think #591 could be expanded to encompass the entire "user focus" bullet? In that case this issue could be narrowed down to the other two bullets.

**Comment by matsduf** [comment]
#591 has been updated to take the entire perspective of a translator.

**Comment by matsduf** [comment]
@mattias-p, how much of this issue has been resolved by #701?

**Comment by matsduf** [comment]
@mattias-p, the instruction for translators have been updated by #772. What remains of this issue?

**Comment by mattias-p** [comment]
I'd say it can be closed. The steps to add a new language are documented (except for the update of the MANIFEST).
@vlevigneron, Do you think the developer documentation for translation good enough?

**Comment by matsduf** [comment]
Documents have been update.
