### ISSUE TITLE
Remove fuzzy entries from fr.po

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#599]
The `share/fr.po` file contains a number of [fuzzy markings](https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html). These entries need to be reviewed by a French translator and possibly updated to make sure the translation is good and that the fuzzy attribute is removed.

Additionally `fr.po` should be removed from the list `@fuzzy_po_files` in `t/po-files.t`. Doing this will make sure we don't merge new fuzzy entries into the develop branch.

**Comment by vlevigneron** [comment]
Fixed in PR https://github.com/zonemaster/zonemaster-engine/pull/644
