### ISSUE TITLE
Remove fuzzy entries from da.po

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#600]
The `share/da.po` file contains a number of fuzzy markings. These entries need to be reviewed by a Danish translator and possibly updated to make sure the translation is good and that the fuzzy attribute is removed.

Additionally `da.po` should be removed from the list `@fuzzy_po_files` in `t/po-files.t`. Doing this will make sure we don't merge new fuzzy entries into the develop branch.

**Comment by matsduf** [comment]
PR #604 created and da.po is updated. File `t/po-files.t` cannot be updated since it currently does not exist in the develop branch.

**Comment by matsduf** [comment]
PR #604 has been merged and resolved the first part of this issue.

**Comment by matsduf** [comment]
@mattias-p, I think this can be closed.

**Comment by mattias-p** [comment]
No, an important purpose of this issue is to close one of the gaps that #596 purposely leaves open. #596 must be merged before this one can be closed.

**Comment by mattias-p** [comment]
Fixed by #640.
