### ISSUE TITLE
Replace source references in checked-in PO files

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#625]
We should not keep source code references (i.e. `#:` comments) in checked-in PO files. They drive diffs all over the PO files making it harder to work with them. See https://github.com/zonemaster/zonemaster-engine/pull/624/files#diff-0c771b7df6621e822f3bf53df2f6fc37R583.

Today the source references serve the purpose of annotating what modules each message tag belongs to. The source references must not be removed without some other means of annotating the relation between message tags and modules.

When designing the alternative annotation, consider the possibility of referring to test case rather than test modules. Keep in mind that the system messages are related to a module, but they are not related to any test case.

**Comment by matsduf** [comment]
A proposal is that the line numbers are replaced by the integer "1" on all lines in a post-process so that we have no line number change in git.

**Comment by mattias-p** [comment]
I considered the source-references-to-line-1 design, but I felt this design was cleaner.

**Comment by matsduf** [comment]
> I considered the source-references-to-line-1 design, but I felt this design was cleaner.

I agree.

@mattias-p, can this be closed now?
