### ISSUE TITLE
Print meaningful message when algorithm is not supported by Zonemaster-LDNS/OpenSSL

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#632]
If Zonemaster-LDNS and OpenSSL does not support the handling of a specific algorithm a confusing message "Unknown cryptographic algorithm" is printed, except if that algorithm is GOST, then "no GOST support" is printed.

Extend the GOST model to the following algorithms in all cases where the algorithm is used in such a way that the message can be generated.

Algorithm number | Algorithm (or description)
:----------------|:-----------------------------------
12               | GOST R 34.10-2001
13               | ECDSA Curve P-256 with SHA-256
14               | ECDSA Curve P-384 with SHA-384
15               | Ed25519
16               | Ed448

**Comment by matsduf** [comment]
PR #633 only resolves this issue in respect to DNSSEC10.

Later PR will resolve the remaining cases in DNSSEC.pm.

**Comment by matsduf** [comment]
PR #641 will resolve the remaining issues.

**Comment by vlevigneron** [comment]
Fixed in PR https://github.com/zonemaster/zonemaster-engine/pull/641
