### ISSUE TITLE
Automate handling of English translation

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#635]
Today we have one version of English strings in the source code, and then we translate them to proper English using en.po. This makes life harder for translators for no good reason. We should put the proper English strings in the source code and do away with the manual handling of en.po - by removing it entirely or otherwise.

**Comment by pawal** [comment]
This goes all the way back to #191 that was closed due to #254. Time to do it proper then. :)

**Comment by matsduf** [comment]
Solution in #745.
