### ISSUE TITLE
Engine Version not updated

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#661]
Zonemaster Engine version shows 3.0.3 as the older one

**Comment by mattias-p** [comment]
Do you know what the correct new Engine version number is? My guess is that it's a major version bump, but I'm not sure. If we had prepared release notes it would be easy to tell. This is why release notes preparation is listed so early in the release process document.

**Comment by matsduf** [comment]
I do not think it is a change in major version. I do not think we have changed the API, so the new version should be v3.1.0. I will create the Changes file (#663).

**Comment by vlevigneron** [comment]
@sandoche2k I modify version number only when I modify the file Engine.pm (this is not the case this time). It is also modified during release process. Do you mind if I close this "issue" ?
