### ISSUE TITLE
Improper implementation of Syntax06

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#669]
The current implementation of SYNTAX06 uses a public resolver to make to MX lookup. The test spec says that we should make the recursion ourselves and respect fake delegation.

**Comment by matsduf** [comment]
@vlevigneron, can you look at this for v2020.1 (not for v2019.2)?

**Comment by matsduf** [comment]
Relates to #610

**Comment by tgreenx** [comment]
Solved by #1063
