### ISSUE TITLE
Optional Net::IP::XS in Backend

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#688]
In order to resolve zonemaster/zonemaster-backend#193 we need to add ip_is_ipv4 to Zonemaster::Net::IP.

**Comment by matsduf** [comment]
@mattias-p, what does that have for implications?

**Comment by matsduf** [comment]
Resolved by #689

**Comment by mattias-p** [comment]
It's just another method in Zonemaster::Net::IP. It won't be called at all by any code in this release.

However after we make the next release, we'd have the option to use the Backend from that release with the Engine from this release in case we need to for some reason.
