### ISSUE TITLE
share/Makefile not compatible with FreeBSD "make"

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#697]
The [share/Makefile] (in current develop branch) is not compatible with FreeBSD `make`(which is *not* GNU Make). The make file contains the GNU Make macros `$(shell ...)` and `$(wildcard ...)` which are not supported by FreeBSD `make`.

The [share/Makefile] is not only used for creating distribution files, as documented in the [ReleaseProcess] document, but is also use for translation work, as documented in the [Translation] document.

A work-around could be to use FreeBSD `gmake` (which *is* GNU Make), but then it should be documented.

All links to documents are to the develop branch of that repository.

[share/Makefile]: https://github.com/zonemaster/zonemaster-engine/blob/develop/share/Makefile
[ReleaseProcess]: https://github.com/zonemaster/zonemaster/blob/develop/docs/internal-documentation/maintenance/ReleaseProcess.md
[Translation]: https://github.com/zonemaster/zonemaster-engine/blob/develop/docs/Translation.pod

**Comment by mattias-p** [comment]
Has this worked before? The `$(shell)` function is new since last release but `$(wildcard)` has been there since 2014. How the `share/Makefile` is invoked has changed over time.

**Comment by matsduf** [comment]
It has probably not worked before either.

**Comment by matsduf** [comment]
PR #726 will resolve this issue.
