### ISSUE TITLE
Convert Translation.pod to Translation.md

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#703]
docs/Translation.pod (see #701) is a POD document. I suggest it is converted to a MD document to make it easier to maintain and link to other documents. I consider the document to be mainly read from Github rather than from the command line. It is not installed with Zonemaster-Engine.

Do you have any objection to conversion? @sandoche2k @vlevigneron @mtoma @pamasse @mattias-p

**Comment by mattias-p** [comment]
I think this matter deserves some discussion of pros and cons.
POD is not only read in the terminal, it's also published on the ZNMSTR area of MetaCPAN, we shouldn't forget that.

Quoting my own comment from https://github.com/zonemaster/zonemaster-engine/pull/701#discussion_r405398041
> It seems MetaCPAN doesn't recognize Markdown as documentation. It doesn't show up in https://metacpan.org/release/Zonemaster-Engine (unless it's located in the root directory where all files get listed no matter the extension). It is possible to browse your way to https://metacpan.org/source/ZNMSTR/Zonemaster-Engine-v3.0.3/docs/Installation.md but the rendering isn't very nice.

If we want to be good citizens of the Perl community we should go with POD.
On the other hand I do agree that ease of maintenance is important.

**Comment by matsduf** [comment]
I agree that we must also consider what is published on CPAN and how. 

An important part of our material is anyhow not included on CPAN since nothing from neither Zonemaster/Zonemaster nor Zonemaster-GUI is packaged there. We should make sure that relevant links are included in the documentation on CPAN, but I think that by keeping all documents in Markdown format we save ourselves a lot of trouble. 

Of course, the documentation in Perl code should still be POD.

**Comment by matsduf** [comment]
Resolved by #772
