### ISSUE TITLE
 Update translation of message strings into Danish

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#706]
Before the release of v2019.2 the translation into French, Swedish and Danish must be updated. For all three languages there are message strings without translation. This issue is for translation into Danish.

Relates to #696 and #705.

@haarbo, is it possible for you to help us with this? Please see updated instructions in "[Translation]", section "For translators".

[Translation]: https://github.com/zonemaster/zonemaster-engine/blob/develop/docs/Translation.pod

**Comment by haarbo** [comment]
Hello Mats

Yes – I would like to help with the translations. Is there a specific deadline or just asap?

Best regards
Niels Haarbo

**Comment by matsduf** [comment]
@haarbo, thank you! If you can do it within a week it would be great. We have a pressure to have the next release completed before May 1. You have my email address and probably even my phone number from previous email communication. Do not hesitate to contact me directly if you need assistance. My Danish is too poor to do it myself. :-)

**Comment by matsduf** [comment]
Resolved by PR #718.
