### ISSUE TITLE
different IPv6 Nameserver IPs in Delegation and Child are not detected

### ISSUE THREAD

**Issue by andreasschulze** [zonemaster/zonemaster-engine#719]
today I changed the IPv6 address of a primary nameserver and expected zonemaster.net to warn about an inconsistent delegation.

- com. delegate example.com to ns1.example.com
  com. anser "example.com/IN/NS" with additional section "ns1.example.com AAAA 2001:db8::1
  which is the old IPv6

- ns1.example.com is moved from 2001:db8::1 to 2001:db8::2
- ns1.example.com answer on both addresses currently

- child is updated, ns1.example.com answer ns1.example.com/IN/AAAA with new 2001:db8::2

- the glue data in the parent zone is currently wrong and will be updated later

- neither https://zonemaster.net nor a lokal instance find this difference

$ zonemaster-cli --version
CLI version:    v2.0.2
Engine version: v3.0.3

Test module versions:
        Address: v1.0.5
        Basic: v1.0.11
        Connectivity: v1.0.14
        Consistency: v1.1.8
        DNSSEC: v1.0.10
        Delegation: v1.0.12
        Example: v1.0.4
        Nameserver: v1.0.23
        Syntax: v1.0.5
        Zone: v1.0.6

$ zonemaster-cli example.com
Seconds Level     Message
======= ========= =======
Looks OK.

Does zonemaster don't care about glue?

**Comment by matsduf** [comment]
I can confirm that there is a bug in the current release, and that the bug has been corrected in the code in the develop branch of Zonemaster-Engine, which will be the base for next release very soon. I have compared the behavior of the current release with a test installation of the code from the develop branch.

The test zone  g.consistency05.exempelvis.se can be used to to verify that code is now correct, and that test zone is included as recorded data in the unit test in the develop branch of Zonemaster-Engine. This test zone is not identical to the scenario described by @andreasschulze, but close enough.

We thank for the report, and close this issue.
