### ISSUE TITLE
Translation language gets stuck on FreeBSD 11 (Engine)

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#748]
Selecting language does not work correctly on FreeBSD 11. After you construct the Zonemaster::Engine::Translator instance and call $translator->locale() with a locale argument, the result is correctly translated to that language. However, if you keep making those calls the translation language argument is no longer respected. Instead locale get stuck on the value from a previous call. 

Fixing this should also fix zonemaster/zonemaster-backend#530.

**Comment by matsduf** [comment]
Resolved by #749
