### ISSUE TITLE
Reduce the number of duplicate messages in dnssec14 test method

### ISSUE THREAD

**Issue by repperille** [zonemaster/zonemaster-engine#769]
When testing a zone for DNSSEC I get a lot of equal messages. In my case 16 messages in two variants

norid.no has got four nameservers (ns.uninett.no. nac.no. server.nordu.net. nn.uninett.no.) using two protocols (IPv4 and IPv6). Each query returns two DNSKEYs.

Example:
`zonemaster-cli --test DNSSEC norid.no`

Result:
Seconds Level     Message
======= ========= =======
   6.23 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.23 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.23 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.23 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.24 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.24 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.24 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.24 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.24 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.24 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.24 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.24 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.25 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.25 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.25 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.25 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).

The code is written so that is collects all nameserver/protocol in the variable %nss (a list of 8 items in my example) then loops that list resulting in two keys per item. 8 * 2 = 16 response messages.

But there are really only two separate messages. One for each key tag. So the resulting test log could be:
Seconds Level     Message
======= ========= =======
   6.22 WARNING   DNSKEY with tag 53884 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).
   6.22 WARNING   DNSKEY with tag 44233 and using algorithm 8 (RSA/SHA-256) has a size (1280) smaller than the recommended one (2048).

Comparing the key tag, algorithm and key size could reduce the number of resulting messages to a unique list.

**Comment by matsduf** [comment]
@repperille, thank you for the report. The specification of DNSSEC14 expected the implementation to create a set for the keys, i.e. one entry, but it creates a list where the key is repeated each time it is found.

**Comment by matsduf** [comment]
@vlevigneron, there is a proposed solution in #770. Please review.
