### ISSUE TITLE
POD in test modules should refer to test specifications

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#780]
The POD documentation in the test modules (e.g. https://metacpan.org/pod/Zonemaster::Engine::Test::Basic) should refer to the test specifications they implement. At the moment we don't have convenient way to link from POD in the implementation to the appropriate version of the specification. Either we come up with a solution to that problem, or otherwise we could probably just link to the latest version.

**Comment by matsduf** [comment]
Closed by #1277
