### ISSUE TITLE
Updated Danish translation

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#810]
New message IDs (msgid) have been created and some have changed. Updated translation of the message strings (msgstr) is needed. The file is found as `share/da.po`. See [Instructions for translators].

[Instructions for translators]: https://github.com/zonemaster/zonemaster-engine/blob/develop/docs/Translation-translators.md

**Comment by matsduf** [comment]
@haarbo, can you help us with this? The release is planned for end of next week. Please see the intructions in the link above, and please reach out for any question or issue.

**Comment by haarbo** [comment]
@matsduf - I have now tried to create a PR with my changes to da.po. I am not sure that I clicked the right buttons. Please let me know if you are able to read my changes to da.po.
