### ISSUE TITLE
Warnings while running Makefiile.PL (CentOS 7)

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#812]
```sh
$ perl Makefile.PL
include /home/sandoche/zonemaster-engine/inc/Module/Install.pm
include inc/Module/Install/Metadata.pm
include inc/Module/Install/Base.pm
include inc/Module/Install/Makefile.pm
include inc/Module/Install/Share.pm
include inc/Module/Install/WriteAll.pm
include inc/Module/Install/Win32.pm
include inc/Module/Install/Can.pm
include inc/Module/Install/Fetch.pm
Warning: prerequisite Clone 0 not found.
Warning: prerequisite File::ShareDir 1 not found.
Warning: prerequisite File::Slurp 0 not found.
Warning: prerequisite IO::Socket::INET6 2.69 not found.
Warning: prerequisite List::MoreUtils 0 not found.
Warning: prerequisite Locale::TextDomain 1.2 not found.
Warning: prerequisite Module::Find 0.1 not found.
Warning: prerequisite Net::IP 1.26 not found.
Warning: prerequisite Pod::Coverage 0 not found.
Warning: prerequisite Readonly 0 not found.
Warning: prerequisite Test::Differences 0 not found.
Warning: prerequisite Test::Exception 0 not found.
Warning: prerequisite Test::Pod 1.22 not found.
Warning: prerequisite Text::CSV 0 not found.
Warning: prerequisite Zonemaster::LDNS 2 not found.
Writing Makefile for Zonemaster::Engine
Writing MYMETA.yml and MYMETA.json
Writing META.yml
```

**Comment by matsduf** [comment]
I think this is OK and can be closed. See my PR that documents this: https://github.com/zonemaster/zonemaster/pull/895

**Comment by sandoche2k** [comment]
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        META.yml
        share/locale/da/LC_MESSAGES/Zonemaster-Engine.mo
        share/locale/fr/LC_MESSAGES/Zonemaster-Engine.mo
        share/locale/nb/LC_MESSAGES/Zonemaster-Engine.mo
        share/locale/sv/LC_MESSAGES/Zonemaster-Engine.mo
Please inform the author.
Warning: prerequisite Readonly 0 not found.
Writing Makefile for Zonemaster::Engine
Writing MYMETA.yml and MYMETA.json
Writing META.yml

**Comment by matsduf** [comment]
All that is covered in PR zonemaster/zonemaster#895, I think, else add a comment there.

This is what the updated document says:

> **Note: You can ignore the following warnings:**
> * Missing META.yml (created by the very same command).
> * Zonemaster-LDNS: Missing ldns source files (fetched by the very same command).
> * Zonemaster-Engine and Zonemaster-CLI: Missing .mo files (created in a later step).
> * Missing prerequisite (only needed on target system), e.g.:
>   * "Warning: prerequisite JSON::XS 0 not found."
