### ISSUE TITLE
Break root hints data out from Perl module

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#850]
Root hints data is stored as a [data section] in `Zonemaster/Engine/Recursor.pm`. For some use cases it can be useful to be able to change that to private root hints data:

* DNS training using a private DNS tree including root and TLDs.
* Zonemaster unit tests making it possible to set up both parent and child in a private tree including TLDs.

To make these use cases possible, put the root hints data was a separate data file. Also make it possible to override that file with a private hints file without updating the perl code.

[data section]: https://github.com/zonemaster/zonemaster-engine/blob/5124989b8a05263b4445aaa181478e0b1f0737a2/lib/Zonemaster/Engine/Recursor.pm#L379-L471

**Comment by mattias-p** [comment]
Ideally we should be keeping around a copy of [named.root](https://www.internic.net/domain/named.root) and parse that during initialization. Given that we can parse it in an acceptable fashion.

**Comment by matsduf** [comment]
Parsing as such should not be a problem, but keep keeping it in json format is not much extra work since it is not updated often. The question is rather how we are triggered to do the update.

**Comment by mattias-p** [comment]
If we keep it in its original format we could have a make target download the current version and diff it against our snapshot.
A possible downside to parsing the original format is that it could introduce additional dependencies.

Another possibility could be if IANA has a mailing list or something for announcements regarding the root hints file.

**Comment by matsduf** [comment]
Resolved by #1134
