### ISSUE TITLE
t/Test-delegation03-C.t fails

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-engine#882]
At the time of release of Zonemaster-Engine v4.1.0 (Zonemaster v2020.2) this unit test worked with the recorded data, but now it doe not. The problem occurs in all environments tested.

```
External query for c.delegation03.exempelvis.se, SOA attempted to abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.ns4.exempelvis.se/2001:2040:2b:1c13::53 while running with no_network at /usr/home/matsd/.cpanm/work/1615535934.1530/Zonemaster-Engine-v4.1.0/blib/lib/Zonemaster/Engine/Recursor.pm line 182.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 3.
t/Test-delegation03-C.t ... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 3 subtests passed 
```

A work-around is to install with `cpanm -n` after conlcuding that all other tests pass.

**Comment by matsduf** [comment]
Resolved by #884

**Comment by pnax** [comment]
> At the time of release of Zonemaster-Engine v4.1.0 (Zonemaster v2020.2) this unit test worked with the recorded data, but now it doe not.

I think I am missing something here. If the recorded data is loaded in cache, how can this test fail at some point if the code wasn't updated ?

**Comment by matsduf** [comment]
As I see it, the test case was partly dependent on external data, and that worked will in the background until that external data was updated. Why it was dependent on that external data is unclear, but I can see that the test case, with the old data
