### ISSUE TITLE
Public Profile ignored after the last upgrade

### ISSUE THREAD

**Issue by godzone** [zonemaster/zonemaster-engine#939]
I have a profile that changes the severity of a number of tests.  After the last upgrade, my overrides do not seem to be used anymore
.  I did not change anything between upgrades but did need to update the backend_config.ini file as the options I had have changed. The profile is being picked up in the config 

[agree-24]bin: zmb profile_names
{"jsonrpc":"2.0","id":1,"result":["godzone","default"]}

Using the API to start a test
zmb start_domain_test --domain xxxxx.co.nz --profile godzone

the profile makes it into the DB params column
 {"domain":"xxxxx.co.nz","priority":10,"profile":"godzone","queue":0} 

But the result of the tests has the default SEVERITY even though I was overriding it.
{"args":{"ns":"ns1.godzone.net.nz/192.138.251.36"},"level
":"ERROR","module":"NAMESERVER","tag":"IS_A_RECURSOR","testcase":"NAMESERVER01","timestamp":67.44314
59903717}

    "logfilter" : {
        "ADDRESS" : {
            "NAMESERVER_IP_WITHOUT_REVERSE" : [
                {
                    "when" : {
                        "ns" : [ "ns3.godzone.net.nz", "ns4.godzone.net.nz" ]
                    },
                    "set" : "NOTICE"
                }
            ]
        },
        "NAMESERVER" : {
            "IS_A_RECURSOR" : [
                {
                    "when" : {
                        "ns" : [ "ns1.godzone.net.nz", "ns2.godzone.net.nz", "ns3.godzone.net.nz", "ns4.godzone.net.nz" ]
                    },
                    "set" : "INFO"
                }
            ],

Not sure what I am missing, this used to work as expected.

**Comment by matsduf** [comment]
@godzone, the argument name has been changed from "ns" to "nsname" which affects the filter function. That is a side affect that we have not thought of. I tested without any filters. Notice the names of the arguments and that the level is WARNING:

```
$ zonemaster-cli --test address godzone.net.nz --level info --no-ipv6 --raw --show_testcase
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.2.1
   2.93 INFO      ADDRESS01      NO_IP_PRIVATE_NETWORK   
  13.95 WARNING   ADDRESS02      NAMESERVER_IP_WITHOUT_REVERSE   ns_ip=2600:1f1c:96e:df00::39; nsname=ns3.godzone.net.nz
  14.61 WARNING   ADDRESS02      NAMESERVER_IP_WITHOUT_REVERSE   ns_ip=2a05:d018:f4a:fa00::41; nsname=ns4.godzone.net.nz
```

Now I created a new profile which is identical to the standard profile besides adding the following filtering statement:
```
    "logfilter" : {
        "ADDRESS" : {
            "NAMESERVER_IP_WITHOUT_REVERSE" : [
                {
                    "when" : {
                        "nsname" : [ "ns3.godzone.net.nz", "ns4.godzone.net.nz" ]
                    },
                    "set" : "NOTICE"
                }
            ]
        }
    },
```
Running the same test with the new profile. Notice that the level is NOTICE now:
```
$ zonemaster-cli --test address godzone.net.nz --level info --no-ipv6 --raw --show_testcase --profile profile-filter.json
Laddar profil från profile-filter.json.
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.2.1
   2.95 INFO      ADDRESS01      NO_IP_PRIVATE_NETWORK   
   8.95 NOTICE    ADDRESS02      NAMESERVER_IP_WITHOUT_REVERSE   ns_ip=2600:1f1c:96e:df00::39; nsname=ns3.godzone.net.nz
   9.66 NOTICE    ADDRESS02      NAMESERVER_IP_WITHOUT_REVERSE   ns_ip=2a05:d018:f4a:fa00::41; nsname=ns4.godzone.net.nz
```

I hope this will answer your question and resolve the issue for you.

**Comment by godzone** [comment]
Hmm, still not working quite right.  If I use the same command as you have above, I get the same result using my profile.  But if I load a test via the api, it doesn't.  It seems my profile is ignored by the backend. My backend_config.ini has the following, which used to work.

[PUBLIC PROFILES]
godzone=/etc/zonemaster/godzone-profile.json

[PRIVATE PROFILES]
#example_profile_2=/example/directory/test2_profile.json

I noted quite a few other changes needed with the database sections, has this changed too

**Comment by matsduf** [comment]
To use a non-default profile via RPCAPI you have to select it in the command. On the server where Backend is running you can try with the following command
```
zmb --verbose start_domain_test --domain godzone.net.nz --profile godzone
```
The command above assumes that RPCAPI runs on localhost and port 5000. Else specify with `--server http://localhost:8080` or what values it should be. If backend is installed on one computer you can use `zmb` and `zmtest` against another computer. `zmb man` and `zmtest`, respectively, will help you.

In Zonemaster-GUI profile `godzone` will be selectable. You can also make that profile the default profile by defining "default".
```
[PUBLIC PROFILES]
default=/etc/zonemaster/godzone-profile.json
```
Now only the godzone profile will be available, and being default. You can define the Zonemaster default profile as a selectable profile by adding that under a new name in the "PUBLIC PROFILES" section.

I hope this helps.

**Comment by matsduf** [comment]
@godzone, have you had time to look at my response on your issue? Does it work for you?

**Comment by matsduf** [comment]
Assumed to be resolved, else a new issue should be created.
